---
- name: uses of tags
  hosts: all
  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
        state: installed
      tags: [ never, beta ]

    - name: install httpd
      yum:
         name: httpd
         state: installed
      tags: [ never, alpha ]
      
